spring:
  datasource:
    url: jdbc:mysql://localhost/staemProject
    username: root
    password: //Inserire la vostra passwors
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop